//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.01 at 10:24:14 PM NZDT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.thymeleaf.org/extras/dialect", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.thymeleaf.extras.eclipse.dialect.xml;
