//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.08 at 08:42:59 PM NZDT 
//


package org.thymeleaf.extras.eclipse.dialect.xml;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 * 				Common data between the 2 Thymeleaf processor types: attribute processors
 * 				and element processors.
 * 			
 * 
 * <p>Java class for Processor complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Processor">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.thymeleaf.org/extras/dialect}DialectItem">
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Processor")
@XmlSeeAlso({
    AttributeProcessor.class,
    ElementProcessor.class
})
public abstract class Processor
    extends DialectItem
{

    
	private String fullname;

	/**
	 * Return the full name of this processor.
	 * 
	 * @return prefix:name
	 */
	public String getFullName() {

		if (fullname == null) {
			fullname = dialect.getPrefix() + ":" + name;
		}
		return fullname;
	}
				
}
