//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.01 at 10:24:14 PM NZDT 
//


package org.thymeleaf.extras.eclipse.dialect.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				A method in an expression object.
 * 			
 * 
 * <p>Java class for ExpressionObjectMethod complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExpressionObjectMethod">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.thymeleaf.org/extras/dialect}DialectItem">
 *       &lt;attribute name="java-bean-property" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExpressionObjectMethod")
public class ExpressionObjectMethod
    extends DialectItem
{

    @XmlAttribute(name = "java-bean-property")
    protected Boolean javaBeanProperty;

    /**
     * Gets the value of the javaBeanProperty property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isJavaBeanProperty() {
        if (javaBeanProperty == null) {
            return false;
        } else {
            return javaBeanProperty;
        }
    }

    /**
     * Sets the value of the javaBeanProperty property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setJavaBeanProperty(Boolean value) {
        this.javaBeanProperty = value;
    }
    
	/**
	 * Return if this expression object method is equal to another one.
	 * 
	 * @param other The expression object method to compare against.
	 * @return <tt>true</tt> if both this and the other method share the same
	 *         name.
	 */
	@Override
	public boolean equals(Object other) {

		return other instanceof ExpressionObjectMethod && name.equals(((ExpressionObjectMethod)other).name);
	}

	/**
	 * Returns a hashcode based on this method data.
	 * 
	 * @return Method hashcode.
	 */
	@Override
	public int hashCode() {

		return name.hashCode();
	}
				
}
